"""PolarSync prototype seed data.

ALL RECORDS ARE SAMPLE / PROTOTYPE CONTENT created for the SIH 2026 demo.
Station names, coordinates and establishment years are public facts; study
titles, authors, abstracts and metrics are illustrative and make no scientific
claims. Abstracts describe scope and methods rather than numerical findings.
"""

UNSPLASH = "https://images.unsplash.com/photo-"


def img(photo_id: str) -> str:
    return UNSPLASH + photo_id


# Verified Unsplash photographs (checked for subject matter)
IMG = {
    "snow_slope": img("1418985991508-e47386d96a71"),
    "nunatak_clouds": img("1458668383970-8ddd3927deed"),
    "gentoo_rock": img("1462888210965-cdf193fb74de"),
    "ocean_calm": img("1468581264429-2548ef9eb732"),
    "ocean_waves": img("1439405326854-014607f694d7"),
    "earth_iss": img("1446776811953-b23d57bd21aa"),
    "earth_night": img("1451187580459-43490279c0fa"),
    "himalaya_ama": img("1454496522488-7a8e488e8606"),
    "aurora_trees": img("1483347756197-71ef80e95f73"),
    "mountain_teal": img("1483728642387-6c3bdd6c93e5"),
    "snow_forest": img("1491002052546-bf38f186af56"),
    "field_researcher": img("1491555103944-7c647fd857e6"),
    "iceberg_lagoon": img("1494564605686-2e931f77a8e2"),
    "clouds_above": img("1499346030926-9a72daac6c63"),
    "peaks_clouds": img("1506905925346-21bda4d32df4"),
    "snow_cabin": img("1517299321609-52687d1bc55a"),
    "king_penguin": img("1517783999520-f068d7431a60"),
    "milkyway_peaks": img("1519681393784-d120267933ba"),
    "norway_flag": img("1520769669658-f07657f5a307"),
    "sky_sun": img("1525490829609-d166ddb58678"),
    "aurora_ice": img("1529963183134-61a90db47eaf"),
    "aurora_snow": img("1531366936337-7c912a4589a7"),
    "chinstrap_snow": img("1551415923-a2297c7fda79"),
    "lake_dusk": img("1561484930-998b6a7b22e8"),
    "aurora_lake": img("1579033461380-adb47c3eb938"),
    "cape_town": img("1580060839134-75a5edca2e99"),
    "himalaya_peak": img("1589802829985-817e51171b92"),
    "gentoo_snow": img("1598439210625-5067c578f3f6"),
    "spiti_mountain": img("1486870591958-9b9d0d1dda99"),
    "underwater": img("1511593358241-7eea1f3c84e5"),
    "ocean_aerial": img("1505118380757-91f5f5632de0"),
    "mountain_sunset": img("1508739773434-c26b3d09e071"),
    "glacial_lake": img("1503614472-8c93d56e92ce"),
    "jagged_peaks": img("1544198365-f5d60b6d8190"),
    "sea_sunset": img("1414609245224-afa02bfb3fda"),
}

# Default thumbnails for uploads without an image, by region
REGION_DEFAULT_IMAGE = {
    "Antarctica": IMG["iceberg_lagoon"],
    "Arctic": IMG["aurora_ice"],
    "Himalaya": IMG["himalaya_peak"],
    "Southern Ocean": IMG["ocean_calm"],
}

ROLES = [
    {"name": "public", "description": "Public visitor – browse and search published content"},
    {"name": "contributor", "description": "Researcher / institution – submit content for review"},
    {"name": "admin", "description": "Repository curator – review, approve and publish content"},
]

# Demo passwords are hashed at seed time
USERS = [
    {"id": "u-alex", "name": "Alex Johnson", "email": "alex@polarsync.in", "password": "polar123", "role": "contributor", "organization": "National Centre for Polar and Ocean Research", "title": "Research Scientist"},
    {"id": "u-admin", "name": "Dr. Kavya Iyer", "email": "admin@polarsync.in", "password": "admin123", "role": "admin", "organization": "PolarSync Editorial Board", "title": "Repository Curator"},
    {"id": "u-priya", "name": "Dr. Priya Sharma", "email": "priya@polarsync.in", "password": "polar123", "role": "contributor", "organization": "National Centre for Polar and Ocean Research", "title": "Glaciologist"},
    {"id": "u-meera", "name": "Dr. Meera Pillai", "email": "meera@polarsync.in", "password": "polar123", "role": "contributor", "organization": "CSIR – National Institute of Oceanography", "title": "Oceanographer"},
    {"id": "u-rajesh", "name": "Dr. Rajesh Kumar", "email": "rajesh@polarsync.in", "password": "polar123", "role": "contributor", "organization": "Wadia Institute of Himalayan Geology", "title": "Cryosphere Scientist"},
    {"id": "u-ananya", "name": "Dr. Ananya Krishnan", "email": "ananya@polarsync.in", "password": "polar123", "role": "contributor", "organization": "National Centre for Polar and Ocean Research", "title": "Atmospheric Scientist"},
    {"id": "u-sanjay", "name": "Dr. Sanjay Nair", "email": "sanjay@polarsync.in", "password": "polar123", "role": "contributor", "organization": "National Centre for Polar and Ocean Research", "title": "Polar Biologist"},
    {"id": "u-farhan", "name": "Dr. Farhan Ali", "email": "farhan@polarsync.in", "password": "polar123", "role": "contributor", "organization": "Geological Survey (collaborating institute)", "title": "Geologist"},
    {"id": "u-arun", "name": "Lt. Cmdr. Arun Das", "email": "arun@polarsync.in", "password": "polar123", "role": "contributor", "organization": "Expedition Logistics & Media Team", "title": "Expedition Photographer"},
]

LOCATIONS = [
    {"id": "loc-maitri", "name": "Maitri Station", "category": "station", "region": "Antarctica", "lat": -70.7667, "lng": 11.7333, "established": 1989,
     "description": "India's permanent Antarctic research station in the Schirmacher Oasis, Dronning Maud Land. Operates year-round and hosts atmospheric, geomagnetic, glaciological and biological observations.",
     "research_areas": ["Atmospheric Science", "Glaciology", "Space Weather", "Polar Biology"], "image": IMG["snow_cabin"]},
    {"id": "loc-bharati", "name": "Bharati Station", "category": "station", "region": "Antarctica", "lat": -69.4083, "lng": 76.1872, "established": 2012,
     "description": "India's newest Antarctic station in the Larsemann Hills on the Prydz Bay coast of East Antarctica, supporting geology, oceanography and coastal ecology research.",
     "research_areas": ["Geology", "Oceanography", "Polar Biology", "Atmospheric Science"], "image": IMG["iceberg_lagoon"]},
    {"id": "loc-dakshin", "name": "Dakshin Gangotri", "category": "station", "region": "Antarctica", "lat": -70.0833, "lng": 12.0, "established": 1983,
     "description": "India's first Antarctic base, established during the third Indian expedition. Later decommissioned and used as a supply and transit base.",
     "research_areas": ["Historical Records", "Logistics"], "image": IMG["nunatak_clouds"]},
    {"id": "loc-himadri", "name": "Himadri Station, Ny-Ålesund", "category": "station", "region": "Arctic", "lat": 78.9236, "lng": 11.931, "established": 2008,
     "description": "India's Arctic research station in the international research village of Ny-Ålesund, Svalbard, focusing on glaciology, atmospheric science and fjord ecology.",
     "research_areas": ["Glaciology", "Atmospheric Science", "Oceanography", "Polar Biology"], "image": IMG["norway_flag"]},
    {"id": "loc-indarc", "name": "IndARC Mooring, Kongsfjorden", "category": "dataset", "region": "Arctic", "lat": 78.98, "lng": 12.25, "established": 2014,
     "description": "India's multi-sensor underwater observatory moored in Kongsfjorden, recording ocean temperature, salinity and currents through the year.",
     "research_areas": ["Oceanography", "Climate Science"], "image": IMG["ocean_calm"]},
    {"id": "loc-brogger", "name": "Vestre Brøggerbreen Glacier", "category": "dataset", "region": "Arctic", "lat": 78.91, "lng": 11.72,
     "description": "Small valley glacier near Ny-Ålesund used for repeat mass-balance and surface-velocity surveys.",
     "research_areas": ["Glaciology", "Remote Sensing"], "image": IMG["snow_slope"]},
    {"id": "loc-himansh", "name": "Himansh Station, Spiti", "category": "station", "region": "Himalaya", "lat": 32.40, "lng": 77.61, "established": 2016,
     "description": "High-altitude research station in the Chandra basin, Himachal Pradesh, supporting glacier, snow and climate observations in the western Himalaya.",
     "research_areas": ["Glaciology", "Hydrology", "Climate Science"], "image": IMG["spiti_mountain"]},
    {"id": "loc-chhota-shigri", "name": "Chhota Shigri Glacier", "category": "dataset", "region": "Himalaya", "lat": 32.28, "lng": 77.53,
     "description": "Benchmark glacier in the Chandra basin with a long record of field mass-balance measurements.",
     "research_areas": ["Glaciology", "Field Observation"], "image": IMG["himalaya_ama"]},
    {"id": "loc-gangotri", "name": "Gangotri Glacier", "category": "dataset", "region": "Himalaya", "lat": 30.93, "lng": 79.08,
     "description": "One of the largest glaciers of the Indian Himalaya and source of the Bhagirathi river; monitored through snout surveys and satellite imagery.",
     "research_areas": ["Glaciology", "Hydrology", "Remote Sensing"], "image": IMG["himalaya_peak"]},
    {"id": "loc-seaice-zone", "name": "Antarctic Sea-Ice Monitoring Zone", "category": "dataset", "region": "Antarctica", "lat": -64.0, "lng": 40.0,
     "description": "Indian-ocean sector of the Antarctic sea-ice zone used as the reference area for the satellite sea-ice extent dataset.",
     "research_areas": ["Remote Sensing", "Glaciology", "Climate Science"], "image": IMG["earth_iss"]},
    {"id": "loc-so-transect", "name": "Southern Ocean Expedition Transect", "category": "expedition", "region": "Southern Ocean", "lat": -52.0, "lng": 45.0,
     "description": "Ship track crossed every austral summer by Indian Antarctic expeditions, used for underway and CTD ocean sampling across the Southern Ocean fronts.",
     "research_areas": ["Oceanography", "Polar Biology"], "image": IMG["ocean_waves"]},
    {"id": "loc-cape-town", "name": "Cape Town Port Call", "category": "expedition", "region": "Southern Ocean", "lat": -33.91, "lng": 18.42,
     "description": "Logistics port where expedition members and cargo transfer to the ice-class vessel before the Southern Ocean crossing.",
     "research_areas": ["Logistics"], "image": IMG["cape_town"]},
    {"id": "loc-prydz", "name": "Prydz Bay Penguin Colonies", "category": "media", "region": "Antarctica", "lat": -68.6, "lng": 77.9,
     "description": "Coastal Adélie penguin colonies near the Larsemann Hills, photographed and monitored during summer field seasons.",
     "research_areas": ["Polar Biology", "Ecology"], "image": IMG["chinstrap_snow"]},
    {"id": "loc-ncpor-goa", "name": "Polar Expedition Flag-off, Goa", "category": "event", "region": "India", "lat": 15.40, "lng": 73.81,
     "description": "Home port and coordination centre for India's polar programme; venue for expedition flag-off ceremonies and public open days.",
     "research_areas": ["Outreach", "Logistics"], "image": IMG["sea_sunset"]},
    {"id": "loc-delhi", "name": "Polar Science Week, New Delhi", "category": "event", "region": "India", "lat": 28.61, "lng": 77.21,
     "description": "Annual public outreach week featuring talks, exhibitions and student quizzes on polar and cryosphere science (sample event).",
     "research_areas": ["Outreach"], "image": IMG["aurora_lake"]},
]


def _c(**kw):
    """Content record with defaults."""
    base = {
        "status": "published",
        "license": "CC BY 4.0",
        "access_level": "Public",
        "keywords": [],
        "related_ids": [],
        "extra": {},
        "citations": 0,
        "downloads": 0,
        "submitted_by": None,
    }
    base.update(kw)
    return base


PAPERS = [
    _c(id="p-iceshelf", content_type="paper", title="Climate Change and Ice Shelf Dynamics in East Antarctica",
       description="Examines how ocean and atmospheric warming influence ice-shelf thinning, basal melt and grounding-line behaviour along the East Antarctic coast using satellite altimetry and field observations.",
       abstract="Ice shelves buttress the flow of grounded ice from the Antarctic ice sheet into the ocean. This study combines satellite altimetry, ice-velocity products and in-situ observations from Indian field campaigns to examine ice-shelf thickness change and basal melt along the coast of Dronning Maud Land and Prydz Bay. Warm-water intrusion beneath the shelves and changes in surface melt are evaluated as drivers of thinning. The implications of ice-shelf change for glacier discharge and future sea-level rise are discussed. Observational records collected near Maitri and Bharati stations are used for validation.",
       region="Antarctica", research_area="Glaciology", author="Dr. Priya Sharma", organization="National Centre for Polar and Ocean Research", year=2026,
       tags=["Ice Shelf", "Climate Change", "Glaciology", "Sea Level", "Remote Sensing"], keywords=["ice shelf", "basal melt", "grounding line", "altimetry", "sea-level rise"],
       thumbnail=IMG["iceberg_lagoon"], file_format="PDF", file_size="2.4 MB", location_ids=["loc-maitri", "loc-bharati"],
       related_ids=["d-seaice", "p-snowacc"], views=1248, citations=34, downloads=310, extra={"doi": "10.0000/polarsync.sample.001"}, created_at="2026-03-12T09:00:00Z"),
    _c(id="p-ozone", content_type="paper", title="Seasonal Ozone Variability over the Antarctic Polar Vortex at Maitri",
       description="Analyses multi-season total-column ozone and ozonesonde profiles from Maitri to characterise the timing and depth of springtime ozone depletion inside the polar vortex.",
       abstract="The Antarctic ozone hole forms each austral spring inside the stratospheric polar vortex. This study analyses total-column ozone measurements and balloon-borne ozonesonde profiles recorded at Maitri Station across several seasons. The onset, depth and recovery of springtime ozone depletion are characterised and related to vortex position and stratospheric temperature. Results are compared with satellite ozone products to assess the consistency of ground-based records. The dataset supports long-term monitoring of ozone recovery under the Montreal Protocol.",
       region="Antarctica", research_area="Atmospheric Science", author="Dr. Ananya Krishnan", organization="National Centre for Polar and Ocean Research", year=2025,
       tags=["Ozone", "Atmospheric Science", "Polar Vortex", "Antarctica"], keywords=["ozone hole", "stratosphere", "ozonesonde", "polar vortex"],
       thumbnail=IMG["sky_sun"], file_format="PDF", file_size="3.1 MB", location_ids=["loc-maitri"], related_ids=["d-ozone-column"],
       views=743, citations=19, downloads=122, created_at="2025-09-05T09:00:00Z"),
    _c(id="p-microplastics", content_type="paper", title="Microplastic Distribution in Southern Ocean Surface Waters",
       description="Survey of microplastic particles in surface seawater collected along the Indian Antarctic expedition route between Cape Town and the Antarctic coast.",
       abstract="Plastic pollution has been reported even in remote polar oceans. This study reports a survey of microplastic particles in surface seawater sampled along the expedition transect from Cape Town to the coast of East Antarctica. Particle abundance, size and polymer type are characterised using filtration and spectroscopic identification. Spatial patterns are examined in relation to ocean fronts, ship traffic and atmospheric transport. The study establishes a baseline for future monitoring of marine pollution in the Southern Ocean.",
       region="Southern Ocean", research_area="Oceanography", author="Dr. Meera Pillai", organization="CSIR – National Institute of Oceanography", year=2025,
       tags=["Marine Pollution", "Oceanography", "Southern Ocean", "Microplastics"], keywords=["microplastics", "pollution", "surface water", "polymer"],
       thumbnail=IMG["ocean_aerial"], file_format="PDF", file_size="4.2 MB", location_ids=["loc-so-transect", "loc-cape-town"], related_ids=["d-ctd"],
       views=2876, citations=64, downloads=540, created_at="2025-04-20T09:00:00Z"),
    _c(id="p-penguins", content_type="paper", title="Adélie Penguins as Bioindicators of Coastal Antarctic Ecosystems",
       description="Multi-season monitoring of Adélie penguin colonies near Bharati Station to assess how sea-ice conditions and food availability relate to breeding success.",
       abstract="Penguins integrate changes across the Southern Ocean food web and are widely used as ecosystem indicators. This study monitors Adélie penguin colonies on the Prydz Bay coast over several breeding seasons using nest counts, photographic surveys and diet sampling. Breeding success is examined alongside local sea-ice conditions and krill availability. The work highlights the value of long-term colony monitoring near Indian stations for detecting ecosystem change.",
       region="Antarctica", research_area="Polar Biology", author="Dr. Sanjay Nair", organization="National Centre for Polar and Ocean Research", year=2026,
       tags=["Penguins", "Polar Biology", "Ecology", "Sea Ice"], keywords=["Adélie penguin", "bioindicator", "breeding success", "krill"],
       thumbnail=IMG["chinstrap_snow"], file_format="PDF", file_size="5.1 MB", location_ids=["loc-prydz", "loc-bharati"], related_ids=["m-penguins", "story-penguins"],
       views=4210, citations=76, downloads=890, created_at="2026-01-20T09:00:00Z"),
    _c(id="p-geomag", content_type="paper", title="Geomagnetic Pulsations and Space-Weather Signatures Observed at Maitri",
       description="Uses magnetometer records from Maitri to study geomagnetic pulsations and their association with solar-wind driven space-weather events.",
       abstract="High-latitude magnetometer stations are sensitive to disturbances driven by the solar wind. This paper analyses fluxgate magnetometer records from Maitri to identify geomagnetic pulsations and substorm signatures. Events are compared with solar-wind parameters and auroral activity to examine coupling between the magnetosphere and ionosphere. The observations contribute to space-weather monitoring from the southern high latitudes.",
       region="Antarctica", research_area="Atmospheric Science", author="Dr. Ananya Krishnan", organization="National Centre for Polar and Ocean Research", year=2024,
       tags=["Space Weather", "Geomagnetism", "Aurora", "Antarctica"], keywords=["geomagnetic pulsations", "magnetometer", "ionosphere", "solar wind"],
       thumbnail=IMG["aurora_snow"], file_format="PDF", file_size="2.7 MB", location_ids=["loc-maitri"], related_ids=["m-aurora-australis"],
       views=612, citations=12, downloads=88, created_at="2024-11-02T09:00:00Z"),
    _c(id="p-larsemann", content_type="paper", title="Holocene Lake Sediment Records from the Larsemann Hills",
       description="Sediment cores from freshwater lakes near Bharati Station are used to reconstruct past climate and deglaciation history in East Antarctica.",
       abstract="Lakes in ice-free coastal oases preserve sediment archives of past environmental change. This study analyses sediment cores from lakes in the Larsemann Hills near Bharati Station. Grain size, geochemistry and biological proxies are combined with radiocarbon dating to reconstruct deglaciation and Holocene climate variability. The records help place present-day change in East Antarctica in a longer palaeoclimate context.",
       region="Antarctica", research_area="Geology", author="Dr. Farhan Ali", organization="Geological Survey (collaborating institute)", year=2025,
       tags=["Geology", "Lake Sediments", "Palaeoclimate", "Antarctica"], keywords=["lake sediments", "Holocene", "deglaciation", "geochemistry"],
       thumbnail=IMG["lake_dusk"], file_format="PDF", file_size="3.8 MB", location_ids=["loc-bharati"],
       views=455, citations=9, downloads=64, created_at="2025-06-18T09:00:00Z"),
    _c(id="p-kongsfjorden", content_type="paper", title="Atlantic Water Intrusion into Kongsfjorden: Insights from the IndARC Mooring",
       description="Year-round mooring records are used to examine how warm Atlantic water enters Kongsfjorden and influences fjord temperature and sea-ice formation.",
       abstract="Arctic fjords on the west coast of Svalbard are exposed to warm Atlantic water carried by the West Spitsbergen Current. This study analyses year-round temperature, salinity and current records from the IndARC mooring in Kongsfjorden. The timing and strength of Atlantic water intrusions are characterised and related to winds and shelf processes. Implications for fjord sea-ice formation, glacier fronts and ecosystems are discussed.",
       region="Arctic", research_area="Oceanography", author="Dr. Meera Pillai", organization="CSIR – National Institute of Oceanography", year=2025,
       tags=["Oceanography", "Arctic", "Climate Change", "Time Series"], keywords=["Atlantic water", "fjord", "mooring", "Kongsfjorden"],
       thumbnail=IMG["ocean_calm"], file_format="PDF", file_size="3.3 MB", location_ids=["loc-indarc", "loc-himadri"], related_ids=["d-indarc"],
       views=820, citations=15, downloads=140, created_at="2025-08-11T09:00:00Z"),
    _c(id="p-blackcarbon", content_type="paper", title="Black Carbon Aerosols in the Arctic Atmosphere at Ny-Ålesund",
       description="Characterises seasonal variation of black carbon aerosols at Himadri and their potential contribution to snow darkening and Arctic warming.",
       abstract="Light-absorbing aerosols such as black carbon can accelerate warming and snowmelt in the Arctic. This study reports aethalometer measurements of black carbon at Ny-Ålesund across seasons. Long-range transport pathways are examined using back-trajectory analysis, and the springtime Arctic haze period is highlighted. The potential radiative effect of deposited black carbon on snow is discussed.",
       region="Arctic", research_area="Atmospheric Science", author="Dr. Ananya Krishnan", organization="National Centre for Polar and Ocean Research", year=2024,
       tags=["Aerosols", "Atmospheric Science", "Arctic", "Climate Change"], keywords=["black carbon", "Arctic haze", "aerosols", "snow albedo"],
       thumbnail=IMG["clouds_above"], file_format="PDF", file_size="2.2 MB", location_ids=["loc-himadri"],
       views=530, citations=11, downloads=77, created_at="2024-07-21T09:00:00Z"),
    _c(id="p-chandra", content_type="paper", title="Glacier Retreat and Debris-Cover Evolution in the Chandra Basin",
       description="Combines multi-decadal satellite imagery and field surveys to map glacier area change and debris cover across the Chandra basin, western Himalaya.",
       abstract="Himalayan glaciers supply meltwater to major South Asian rivers. This study maps glacier outlines and debris cover in the Chandra basin using Landsat and Sentinel imagery spanning several decades, validated with field surveys from Himansh station. Patterns of glacier retreat are examined with respect to glacier size, elevation and debris thickness. The results inform hydrological assessments of future meltwater supply.",
       region="Himalaya", research_area="Glaciology", author="Dr. Rajesh Kumar", organization="Wadia Institute of Himalayan Geology", year=2025,
       tags=["Glaciology", "Himalaya", "Remote Sensing", "Climate Change"], keywords=["glacier retreat", "debris cover", "Landsat", "Chandra basin"],
       thumbnail=IMG["himalaya_ama"], file_format="PDF", file_size="6.0 MB", location_ids=["loc-himansh", "loc-chhota-shigri"], related_ids=["d-massbalance", "r-himalaya"],
       views=1980, citations=41, downloads=420, created_at="2025-05-14T09:00:00Z"),
    _c(id="p-permafrost", content_type="paper", title="Rock Glaciers and Mountain Permafrost in the Western Himalaya",
       description="Inventory of rock glaciers in the Spiti and Chandra valleys used to estimate the distribution of mountain permafrost and its hydrological importance.",
       abstract="Mountain permafrost is poorly mapped in the Himalaya. This study compiles an inventory of active and relict rock glaciers from high-resolution imagery in the Spiti and Chandra valleys. Rock-glacier distribution is used as an indicator of permafrost occurrence, and ground temperature loggers provide local validation. The potential water storage in rock glaciers and their response to warming are discussed.",
       region="Himalaya", research_area="Geology", author="Dr. Farhan Ali", organization="Geological Survey (collaborating institute)", year=2024,
       tags=["Permafrost", "Cryosphere", "Himalaya", "Geology"], keywords=["rock glacier", "permafrost", "Spiti", "ground temperature"],
       thumbnail=IMG["spiti_mountain"], file_format="PDF", file_size="3.6 MB", location_ids=["loc-himansh"],
       views=402, citations=7, downloads=51, created_at="2024-10-03T09:00:00Z"),
    _c(id="p-microbial", content_type="paper", title="Microbial Mats in Freshwater Lakes of the Schirmacher Oasis",
       description="Describes the diversity of cyanobacterial microbial mats in lakes near Maitri and their adaptation to extreme cold and light conditions.",
       abstract="Freshwater lakes in Antarctic oases host microbial mats dominated by cyanobacteria. This study samples mats from several lakes in the Schirmacher Oasis near Maitri and characterises community composition using microscopy and DNA sequencing. Adaptations to freezing, desiccation and seasonal light are discussed. The lakes are presented as sensitive indicators of environmental change in East Antarctica.",
       region="Antarctica", research_area="Polar Biology", author="Dr. Sanjay Nair", organization="National Centre for Polar and Ocean Research", year=2025,
       tags=["Microbiology", "Polar Biology", "Lake Sediments", "Antarctica"], keywords=["cyanobacteria", "microbial mats", "Schirmacher Oasis", "freshwater lakes"],
       thumbnail=IMG["glacial_lake"], file_format="PDF", file_size="2.9 MB", location_ids=["loc-maitri"],
       views=388, citations=8, downloads=45, created_at="2025-03-02T09:00:00Z"),
    _c(id="p-phyto", content_type="paper", title="Southern Ocean Fronts and Phytoplankton Bloom Dynamics",
       description="Links satellite chlorophyll and ship-based observations to the position of Southern Ocean fronts and the timing of summer phytoplankton blooms.",
       abstract="Phytoplankton blooms in the Southern Ocean underpin the polar food web and influence carbon uptake. This study combines ship-based chlorophyll and nutrient measurements from expedition transects with satellite ocean-colour data. Bloom timing and intensity are examined across the Subtropical, Subantarctic and Polar fronts and near the sea-ice edge. The role of iron availability and stratification is discussed.",
       region="Southern Ocean", research_area="Oceanography", author="Dr. Meera Pillai", organization="CSIR – National Institute of Oceanography", year=2026,
       tags=["Phytoplankton", "Ocean Fronts", "Oceanography", "Remote Sensing"], keywords=["chlorophyll", "phytoplankton bloom", "polar front", "ocean colour"],
       thumbnail=IMG["ocean_waves"], file_format="PDF", file_size="3.9 MB", location_ids=["loc-so-transect", "loc-seaice-zone"], related_ids=["d-ctd"],
       views=690, citations=10, downloads=93, created_at="2026-02-09T09:00:00Z"),
    _c(id="p-snowacc", content_type="paper", title="Snow Accumulation Variability in Coastal Dronning Maud Land",
       description="Uses stake networks and shallow firn cores near Maitri to examine year-to-year variability in snow accumulation and surface mass balance.",
       abstract="Snow accumulation controls the surface mass balance of the Antarctic ice sheet. This study combines stake-network measurements and shallow firn cores collected inland of Maitri to examine interannual variability in snow accumulation. Accumulation is compared with reanalysis precipitation and atmospheric circulation patterns. The results help evaluate how coastal Antarctic accumulation responds to a changing climate.",
       region="Antarctica", research_area="Glaciology", author="Dr. Priya Sharma", organization="National Centre for Polar and Ocean Research", year=2024,
       tags=["Snow", "Glaciology", "Ice Core", "Antarctica"], keywords=["snow accumulation", "firn core", "surface mass balance", "stake network"],
       thumbnail=IMG["snow_slope"], file_format="PDF", file_size="2.1 MB", location_ids=["loc-maitri"], related_ids=["p-iceshelf"],
       views=505, citations=9, downloads=70, created_at="2024-06-30T09:00:00Z"),
    _c(id="p-monsoon", content_type="paper", title="Arctic Sea Ice Variability and Possible Links to the Indian Summer Monsoon",
       description="Explores statistical associations between Arctic sea-ice anomalies and Indian summer monsoon rainfall; the physical mechanisms remain under investigation.",
       abstract="Teleconnections between the polar regions and the tropics are an active research topic. This study explores statistical associations between Arctic sea-ice anomalies and Indian summer monsoon rainfall using reanalysis and satellite records. Possible atmospheric pathways are examined with composite analysis. The paper emphasises that the proposed links are debated and require further modelling studies before firm conclusions can be drawn.",
       region="Arctic", research_area="Climate Science", author="Alex Johnson", organization="National Centre for Polar and Ocean Research", year=2025,
       tags=["Sea Ice", "Monsoon", "Climate Change", "Arctic"], keywords=["teleconnection", "Indian monsoon", "Arctic sea ice", "reanalysis"],
       thumbnail=IMG["aurora_trees"], file_format="PDF", file_size="2.6 MB", location_ids=["loc-himadri"], related_ids=["r-arctic"],
       views=1530, citations=22, downloads=260, submitted_by="u-alex", created_at="2025-07-07T09:00:00Z"),
    _c(id="p-brogger", content_type="paper", title="Surface Mass Balance of Vestre Brøggerbreen, Svalbard",
       description="Field stake measurements and GNSS surveys are used to track the surface mass balance and thinning of a small Arctic valley glacier near Himadri.",
       abstract="Small Arctic glaciers respond quickly to climate warming. This study reports glaciological mass-balance measurements on Vestre Brøggerbreen near Ny-Ålesund using stake networks, snow pits and GNSS surveys. Seasonal winter accumulation and summer ablation are quantified and compared with local meteorological records. The record contributes to international glacier monitoring in Svalbard.",
       region="Arctic", research_area="Glaciology", author="Alex Johnson", organization="National Centre for Polar and Ocean Research", year=2026,
       tags=["Glaciology", "Arctic", "Field Observation", "Climate Change"], keywords=["mass balance", "Svalbard", "glacier", "GNSS"],
       thumbnail=IMG["snow_forest"], file_format="PDF", file_size="2.3 MB", location_ids=["loc-brogger", "loc-himadri"],
       views=410, citations=3, downloads=58, submitted_by="u-alex", created_at="2026-05-19T09:00:00Z"),
    _c(id="p-seaice-remote", content_type="paper", title="Satellite Passive-Microwave Retrieval of Antarctic Sea Ice Concentration",
       description="Evaluates passive-microwave algorithms for retrieving sea-ice concentration in the Indian Ocean sector of the Southern Ocean against ship-based ice observations.",
       abstract="Satellite passive-microwave sensors provide the longest continuous record of sea ice. This study compares several sea-ice concentration algorithms in the Indian Ocean sector of Antarctica against ship-based visual ice observations made during expedition voyages. Algorithm performance near the ice edge and in thin-ice conditions is assessed. The evaluation informs the processing of the PolarSync Antarctic sea-ice extent dataset.",
       region="Antarctica", research_area="Remote Sensing", author="Alex Johnson", organization="National Centre for Polar and Ocean Research", year=2025,
       tags=["Sea Ice", "Remote Sensing", "Antarctica", "Satellite"], keywords=["passive microwave", "sea ice concentration", "validation", "satellite"],
       thumbnail=IMG["earth_iss"], file_format="PDF", file_size="3.0 MB", location_ids=["loc-seaice-zone"], related_ids=["d-seaice"],
       views=720, citations=13, downloads=118, submitted_by="u-alex", created_at="2025-02-25T09:00:00Z"),
]

DATASETS = [
    _c(id="d-seaice", content_type="dataset", title="Antarctic Sea Ice Extent Dataset (2010–2026)",
       description="Daily, monthly and annual Antarctic sea-ice extent and concentration derived from satellite passive-microwave observations, with a focus on the Indian Ocean sector.",
       abstract="This dataset provides gridded sea-ice concentration and derived sea-ice extent for the Antarctic, processed from satellite passive-microwave brightness temperatures. Daily fields are aggregated to monthly and annual means. Regional time series are provided for the Indian Ocean sector near Maitri and Bharati. Quality flags mark periods affected by sensor transitions.",
       region="Antarctica", research_area="Remote Sensing", author="NCPOR Remote Sensing Team", organization="National Centre for Polar and Ocean Research", year=2026,
       tags=["Sea Ice", "Remote Sensing", "Time Series", "Antarctica", "Climate Change"], keywords=["sea ice extent", "satellite", "passive microwave", "time series"],
       thumbnail=IMG["earth_iss"], file_format="CSV / GeoTIFF", file_size="1.2 GB", location_ids=["loc-seaice-zone"], related_ids=["p-seaice-remote", "p-iceshelf"],
       views=892, citations=21, downloads=640,
       extra={"coverage": "2010–2026", "temporal_resolution": "Daily", "spatial_resolution": "25 km grid", "variables": ["sea_ice_concentration", "sea_ice_extent", "quality_flag"]},
       created_at="2026-01-10T09:00:00Z"),
    _c(id="d-methane", content_type="dataset", title="Arctic Methane and CO₂ Flux Measurements — Ny-Ålesund (2023–2025)",
       description="Eddy-covariance measurements of methane and carbon dioxide fluxes over Arctic tundra near Himadri station.",
       abstract="Continuous eddy-covariance flux measurements of methane and carbon dioxide over tundra near Ny-Ålesund. High-frequency data are processed to half-hourly fluxes with quality control and gap-filling. Supporting meteorological and soil variables are included to help interpret seasonal greenhouse gas exchange in the Arctic.",
       region="Arctic", research_area="Atmospheric Science", author="Arctic Research Team", organization="National Centre for Polar and Ocean Research", year=2025,
       tags=["Greenhouse Gases", "Arctic", "Time Series", "Atmospheric Science"], keywords=["methane", "carbon dioxide", "eddy covariance", "tundra"],
       thumbnail=IMG["aurora_ice"], file_format="NetCDF / CSV", file_size="458 MB", location_ids=["loc-himadri"],
       views=531, citations=11, downloads=205, extra={"coverage": "2023–2025", "temporal_resolution": "30 min"}, created_at="2025-11-20T09:00:00Z"),
    _c(id="d-massbalance", content_type="dataset", title="Chhota Shigri Glacier Mass Balance Dataset",
       description="Annual and seasonal glaciological mass-balance measurements from stake and pit networks on the Chhota Shigri benchmark glacier.",
       abstract="Field glaciological measurements from the Chhota Shigri glacier in the Chandra basin, including stake ablation, snow-pit accumulation and derived annual and seasonal mass balance by elevation band. Metadata document survey dates, stake positions and uncertainty estimates.",
       region="Himalaya", research_area="Glaciology", author="Cryosphere Research Group", organization="Wadia Institute of Himalayan Geology", year=2025,
       tags=["Glaciology", "Himalaya", "Field Observation", "Time Series"], keywords=["mass balance", "benchmark glacier", "stake network", "Chandra basin"],
       thumbnail=IMG["himalaya_ama"], file_format="Excel / NetCDF", file_size="245 MB", location_ids=["loc-chhota-shigri", "loc-himansh"], related_ids=["p-chandra", "r-himalaya"],
       views=1654, citations=42, downloads=512, extra={"coverage": "2002–2025", "temporal_resolution": "Seasonal"}, created_at="2025-07-15T09:00:00Z"),
    _c(id="d-maitri-aws", content_type="dataset", title="Maitri Automatic Weather Station Records (2015–2025)",
       description="Hourly air temperature, pressure, humidity, wind and radiation records from the automatic weather station at Maitri.",
       abstract="Quality-controlled hourly meteorological observations from the automatic weather station at Maitri Station, Schirmacher Oasis. Variables include air temperature, station pressure, relative humidity, wind speed and direction, and incoming shortwave radiation. Gaps and sensor changes are documented in the metadata.",
       region="Antarctica", research_area="Atmospheric Science", author="Maitri Meteorology Unit", organization="National Centre for Polar and Ocean Research", year=2025,
       tags=["Weather Observation", "Time Series", "Antarctica", "Atmospheric Science"], keywords=["automatic weather station", "air temperature", "wind", "Maitri"],
       thumbnail=IMG["snow_cabin"], file_format="CSV", file_size="96 MB", location_ids=["loc-maitri"],
       views=760, citations=14, downloads=388, extra={"coverage": "2015–2025", "temporal_resolution": "Hourly"}, created_at="2025-12-01T09:00:00Z"),
    _c(id="d-ozone-column", content_type="dataset", title="Maitri Total Ozone Column Observations",
       description="Ground-based total-column ozone and ozonesonde profile data recorded at Maitri during austral spring campaigns.",
       abstract="Daily total-column ozone values and periodic ozonesonde vertical profiles from Maitri Station. Includes instrument calibration notes and comparison flags against satellite ozone products. Supports studies of the Antarctic ozone hole and its long-term recovery.",
       region="Antarctica", research_area="Atmospheric Science", author="Dr. Ananya Krishnan", organization="National Centre for Polar and Ocean Research", year=2025,
       tags=["Ozone", "Atmospheric Science", "Time Series", "Antarctica"], keywords=["total ozone", "ozonesonde", "stratosphere", "Maitri"],
       thumbnail=IMG["sky_sun"], file_format="CSV", file_size="38 MB", location_ids=["loc-maitri"], related_ids=["p-ozone"],
       views=402, citations=6, downloads=150, extra={"coverage": "2016–2025", "temporal_resolution": "Daily"}, created_at="2025-10-14T09:00:00Z"),
    _c(id="d-indarc", content_type="dataset", title="IndARC Mooring Temperature and Salinity Time Series (Kongsfjorden)",
       description="Multi-depth ocean temperature, salinity and current records from India's IndARC mooring in Kongsfjorden, Svalbard.",
       abstract="Year-round time series from the IndARC multi-sensor mooring in Kongsfjorden. Records include temperature and conductivity at several depths, derived salinity and acoustic current profiles. Data are delivered per deployment year with calibration and quality flags.",
       region="Arctic", research_area="Oceanography", author="Arctic Oceanography Group", organization="National Centre for Polar and Ocean Research", year=2025,
       tags=["Oceanography", "Arctic", "Time Series"], keywords=["mooring", "salinity", "temperature", "Kongsfjorden"],
       thumbnail=IMG["ocean_calm"], file_format="NetCDF", file_size="310 MB", location_ids=["loc-indarc"], related_ids=["p-kongsfjorden"],
       views=388, citations=9, downloads=131, extra={"coverage": "2014–2025", "temporal_resolution": "Hourly"}, created_at="2025-09-02T09:00:00Z"),
    _c(id="d-ctd", content_type="dataset", title="Southern Ocean CTD Profiles — Expedition Transects",
       description="Conductivity-temperature-depth profiles collected at stations along the Indian Antarctic expedition route across the Southern Ocean fronts.",
       abstract="Ship-based CTD casts collected at hydrographic stations between Cape Town and the Antarctic coast during summer expeditions. Profiles include temperature, salinity, dissolved oxygen and fluorescence. Station metadata identify the frontal zone of each cast.",
       region="Southern Ocean", research_area="Oceanography", author="Southern Ocean Expedition Team", organization="CSIR – National Institute of Oceanography", year=2026,
       tags=["Oceanography", "Southern Ocean", "Ocean Fronts", "Expedition"], keywords=["CTD", "hydrography", "Southern Ocean fronts", "salinity"],
       thumbnail=IMG["ocean_waves"], file_format="CSV / NetCDF", file_size="120 MB", location_ids=["loc-so-transect"], related_ids=["p-phyto", "p-microplastics"],
       views=455, citations=7, downloads=176, extra={"coverage": "2018–2026", "temporal_resolution": "Per cast"}, created_at="2026-04-04T09:00:00Z"),
    _c(id="d-gangotri", content_type="dataset", title="Gangotri Glacier Snout Position Survey Records",
       description="Repeat field and satellite-derived positions of the Gangotri glacier snout, compiled for monitoring glacier retreat.",
       abstract="Compilation of Gangotri glacier terminus positions from repeat field surveys and satellite imagery. Each record includes survey method, date and positional uncertainty. The dataset supports analysis of long-term glacier retreat and comparison with climate records.",
       region="Himalaya", research_area="Glaciology", author="Himalayan Glacier Monitoring Group", organization="Wadia Institute of Himalayan Geology", year=2024,
       tags=["Glaciology", "Himalaya", "Remote Sensing", "Climate Change"], keywords=["glacier snout", "retreat", "Gangotri", "repeat survey"],
       thumbnail=IMG["himalaya_peak"], file_format="GeoJSON / CSV", file_size="12 MB", location_ids=["loc-gangotri"], related_ids=["r-himalaya"],
       views=980, citations=18, downloads=301, extra={"coverage": "1990–2024", "temporal_resolution": "Annual"}, created_at="2024-12-12T09:00:00Z"),
]

REPORTS = [
    _c(id="r-himalaya", content_type="report", title="Himalayan Cryosphere Status Report 2025",
       description="Annual overview of glacier, snow-cover and permafrost monitoring across Indian Himalayan benchmark sites, with recommendations for observation networks.",
       abstract="This status report summarises monitoring of Himalayan glaciers, seasonal snow cover and mountain permafrost conducted at Indian benchmark sites during the 2024–25 hydrological year. It reviews field mass-balance programmes, satellite snow-cover products and new permafrost observations. The report identifies gaps in high-altitude observation networks and recommends priorities for long-term monitoring and data sharing.",
       region="Himalaya", research_area="Glaciology", author="Dr. Rajesh Kumar", organization="Wadia Institute of Himalayan Geology", year=2025,
       tags=["Cryosphere", "Himalaya", "Glaciology", "Snow", "Policy"], keywords=["status report", "snow cover", "glaciers", "permafrost"],
       thumbnail=IMG["peaks_clouds"], file_format="PDF", file_size="6.8 MB", location_ids=["loc-himansh", "loc-gangotri", "loc-chhota-shigri"], related_ids=["d-massbalance", "p-chandra"],
       views=2103, citations=57, downloads=730, created_at="2025-12-10T09:00:00Z"),
    _c(id="r-iae", content_type="report", title="Indian Antarctic Expedition — Science Summary Report (2024–25)",
       description="Summary of science programmes, logistics and field activities carried out at Maitri, Bharati and aboard ship during the austral summer season.",
       abstract="This report summarises the science conducted during the 2024–25 Indian Antarctic expedition. It covers atmospheric, glaciological, geological, biological and oceanographic programmes at Maitri and Bharati stations and along the ship transect. Logistics, environmental management and outreach activities are also described.",
       region="Antarctica", research_area="Climate Science", author="Expedition Science Team", organization="National Centre for Polar and Ocean Research", year=2025,
       tags=["Expedition", "Antarctica", "Research Station", "Field Observation"], keywords=["expedition report", "Maitri", "Bharati", "field season"],
       thumbnail=IMG["field_researcher"], file_format="PDF", file_size="12.4 MB", location_ids=["loc-maitri", "loc-bharati", "loc-so-transect"], related_ids=["exp-antarctic-2026"],
       views=3420, citations=89, downloads=990, created_at="2025-08-15T09:00:00Z"),
    _c(id="r-arctic", content_type="report", title="Arctic Sea Ice Seasonal Assessment 2025",
       description="Assessment of the 2025 Arctic sea-ice season including the September minimum, regional anomalies and comparison with the satellite record.",
       abstract="This assessment reviews the 2025 Arctic sea-ice season using satellite sea-ice extent and thickness products. It describes the timing of the seasonal minimum, regional anomalies in the Barents and Kara seas and the atmospheric conditions during the melt season. Observations from the Indian Arctic station at Ny-Ålesund provide local context.",
       region="Arctic", research_area="Climate Science", author="Arctic Science Group", organization="National Centre for Polar and Ocean Research", year=2025,
       tags=["Sea Ice", "Arctic", "Climate Change", "Remote Sensing"], keywords=["Arctic sea ice", "seasonal minimum", "assessment"],
       thumbnail=IMG["aurora_lake"], file_format="PDF", file_size="8.9 MB", location_ids=["loc-himadri"], related_ids=["p-monsoon"],
       views=3102, citations=48, downloads=802, created_at="2025-10-01T09:00:00Z"),
    _c(id="r-bharati-env", content_type="report", title="Bharati Station Environmental Monitoring Report 2025",
       description="Annual report on waste management, emissions, water quality and wildlife-disturbance monitoring at Bharati Station under the Antarctic environmental protocol.",
       abstract="This report documents environmental monitoring at Bharati Station, including fuel use and emissions, waste handling, wastewater quality and observations of wildlife near station infrastructure. It describes compliance with environmental protection obligations for Antarctic operations and lists improvement actions for the next season.",
       region="Antarctica", research_area="Polar Biology", author="Station Environment Officer", organization="National Centre for Polar and Ocean Research", year=2025,
       tags=["Policy", "Research Station", "Antarctica", "Ecology"], keywords=["environmental monitoring", "Bharati", "waste management", "protocol"],
       thumbnail=IMG["gentoo_rock"], file_format="PDF", file_size="4.4 MB", location_ids=["loc-bharati"],
       views=640, citations=4, downloads=120, created_at="2025-11-05T09:00:00Z"),
    _c(id="r-arctic-programme", content_type="report", title="Indian Arctic Programme — Annual Science Summary 2025",
       description="Overview of glaciology, atmospheric, oceanographic and biological research carried out at Himadri and the IndARC mooring during 2025.",
       abstract="This annual summary describes research carried out under the Indian Arctic programme at Himadri station in Ny-Ålesund and through the IndARC mooring in Kongsfjorden. Highlights include glacier mass-balance surveys, aerosol and greenhouse gas monitoring, fjord oceanography and studies of Arctic ecosystems. International collaborations and student training activities are also listed.",
       region="Arctic", research_area="Climate Science", author="Arctic Programme Office", organization="National Centre for Polar and Ocean Research", year=2025,
       tags=["Arctic", "Research Station", "Expedition", "Climate Change"], keywords=["Arctic programme", "Himadri", "annual summary"],
       thumbnail=IMG["norway_flag"], file_format="PDF", file_size="7.2 MB", location_ids=["loc-himadri", "loc-indarc"], related_ids=["exp-arctic-2025"],
       views=920, citations=10, downloads=210, created_at="2026-01-28T09:00:00Z"),
]

MEDIA = [
    _c(id="m-exp-video", content_type="video", title="Antarctic Expedition 2026 — Voyage Highlights",
       description="Highlights from the 2026 Antarctic expedition: departure from Goa, the Southern Ocean crossing, sea-ice navigation and arrival at Maitri.",
       region="Antarctica", research_area="Outreach", author="Expedition Media Team", organization="National Centre for Polar and Ocean Research", year=2026,
       tags=["Expedition", "Documentary", "Antarctica", "Research Station"], thumbnail=IMG["nunatak_clouds"], location_ids=["loc-maitri", "loc-so-transect"],
       related_ids=["exp-antarctic-2026"], views=5120, extra={"duration": "12:34", "expedition_id": "exp-antarctic-2026", "caption": "Departure to arrival in twelve minutes."}, created_at="2026-03-15T09:00:00Z"),
    _c(id="m-penguins", content_type="photo", title="Penguins of the Antarctic Coast",
       description="Illustrative photographs of penguins on snow and rock, representing the colony surveys carried out each summer near Bharati Station.",
       region="Antarctica", research_area="Polar Biology", author="Dr. Sanjay Nair", organization="National Centre for Polar and Ocean Research", year=2026,
       tags=["Penguins", "Wildlife", "Antarctica", "Photography"], thumbnail=IMG["chinstrap_snow"], location_ids=["loc-prydz", "loc-bharati"],
       related_ids=["p-penguins"], views=3890, extra={"image_count": 48, "photographer": "Dr. Sanjay Nair", "gallery": [IMG["chinstrap_snow"], IMG["gentoo_snow"], IMG["gentoo_rock"], IMG["king_penguin"]], "caption": "Colony survey, January 2026."}, created_at="2026-01-20T09:00:00Z"),
    _c(id="m-aurora-ny", content_type="photo", title="Aurora Borealis over Ny-Ålesund",
       description="Time-lapse stills of the northern lights photographed from Himadri during the polar night.",
       region="Arctic", research_area="Space Weather", author="Dr. Vikram Mehta", organization="Indian Arctic Programme", year=2025,
       tags=["Aurora", "Arctic", "Photography", "Space Weather"], thumbnail=IMG["aurora_ice"], location_ids=["loc-himadri"],
       views=6240, extra={"image_count": 72, "photographer": "Dr. Vikram Mehta", "gallery": [IMG["aurora_ice"], IMG["aurora_trees"], IMG["aurora_lake"]], "caption": "Polar night over Kongsfjorden."}, created_at="2025-11-10T09:00:00Z"),
    _c(id="m-vessel", content_type="video", title="Crossing the Southern Ocean",
       description="On-deck footage of the expedition vessel crossing the Southern Ocean fronts, including CTD deployment and iceberg sightings.",
       region="Southern Ocean", research_area="Oceanography", author="Expedition Media Team", organization="National Centre for Polar and Ocean Research", year=2025,
       tags=["Expedition", "Oceanography", "Research Vessel", "Southern Ocean"], thumbnail=IMG["ocean_calm"], location_ids=["loc-so-transect"],
       related_ids=["d-ctd"], views=2210, extra={"duration": "8:12", "expedition_id": "exp-antarctic-2026"}, created_at="2025-12-05T09:00:00Z"),
    _c(id="m-gangotri", content_type="photo", title="Gangotri Glacier — Repeat Photography",
       description="Repeat photographs of the Gangotri glacier region used alongside satellite imagery to document glacier change.",
       region="Himalaya", research_area="Glaciology", author="Himalayan Glacier Monitoring Group", organization="Wadia Institute of Himalayan Geology", year=2025,
       tags=["Glaciology", "Himalaya", "Photography", "Climate Change"], thumbnail=IMG["himalaya_peak"], location_ids=["loc-gangotri"],
       related_ids=["d-gangotri"], views=1870, extra={"image_count": 120, "photographer": "Field Survey Team", "gallery": [IMG["himalaya_peak"], IMG["himalaya_ama"], IMG["peaks_clouds"]]}, created_at="2025-09-15T09:00:00Z"),
    _c(id="m-press-flagoff", content_type="press_release", title="Antarctic Expedition 2026 Flagged Off from Goa",
       description="Press release (sample): the 2026 Indian Antarctic expedition departs Goa with teams for atmospheric, glaciological, geological and biological research.",
       abstract="The 2026 Indian Antarctic expedition was flagged off from Goa. Expedition members will travel via Cape Town to Maitri and Bharati stations, where they will relieve the wintering teams and carry out summer science programmes in atmospheric science, glaciology, geology and polar biology. (Sample press release created for the PolarSync prototype.)",
       region="India", research_area="Outreach", author="Media Cell", organization="PolarSync Prototype (sample)", year=2025,
       tags=["Press Release", "Expedition", "Antarctica"], thumbnail=IMG["sea_sunset"], location_ids=["loc-ncpor-goa"], related_ids=["exp-antarctic-2026"],
       views=1450, created_at="2025-11-28T09:00:00Z"),
    _c(id="m-icebergs", content_type="photo", title="Tabular Icebergs off the East Antarctic Coast",
       description="Icebergs calved from East Antarctic ice shelves, photographed from the ship's bridge on approach to the coast.",
       region="Antarctica", research_area="Glaciology", author="Expedition Media Team", organization="National Centre for Polar and Ocean Research", year=2024,
       tags=["Icebergs", "Ice Shelf", "Antarctica", "Photography"], thumbnail=IMG["iceberg_lagoon"], location_ids=["loc-bharati"],
       related_ids=["p-iceshelf"], views=2980, extra={"image_count": 95, "photographer": "Expedition Media Team", "gallery": [IMG["iceberg_lagoon"], IMG["nunatak_clouds"], IMG["snow_slope"]]}, created_at="2024-02-10T09:00:00Z"),
    _c(id="m-press-portal", content_type="press_release", title="PolarSync Opens Public Access to Polar Research Records",
       description="Sample announcement of the PolarSync portal providing one gateway to polar research, data, media and outreach material.",
       abstract="PolarSync brings research papers, datasets, expedition media and educational resources from India's polar programme into a single searchable portal. Contributions go through an AI-assisted, human-reviewed publication workflow. (Sample press release for the SIH 2026 prototype.)",
       region="India", research_area="Outreach", author="Media Cell", organization="PolarSync Prototype (sample)", year=2026,
       tags=["Press Release", "Outreach", "Policy"], thumbnail=IMG["earth_night"], location_ids=["loc-delhi"],
       views=980, created_at="2026-08-22T09:00:00Z"),
    _c(id="m-maitri-winter", content_type="photo", title="Maitri Station in the Polar Winter",
       description="Station buildings and instruments under winter snow at Maitri, photographed by the wintering team.",
       region="Antarctica", research_area="Outreach", author="Wintering Team", organization="National Centre for Polar and Ocean Research", year=2025,
       tags=["Research Station", "Antarctica", "Photography", "Maitri"], thumbnail=IMG["snow_cabin"], location_ids=["loc-maitri"],
       views=2140, extra={"image_count": 36, "photographer": "Wintering Team", "gallery": [IMG["snow_cabin"], IMG["snow_forest"], IMG["snow_slope"]]}, created_at="2025-07-01T09:00:00Z"),
    _c(id="m-aurora-australis", content_type="photo", title="Aurora Australis over the Schirmacher Oasis",
       description="The southern lights recorded by Maitri's all-sky camera team during the polar night.",
       region="Antarctica", research_area="Space Weather", author="Wintering Team", organization="National Centre for Polar and Ocean Research", year=2025,
       tags=["Aurora", "Antarctica", "Space Weather", "Photography"], thumbnail=IMG["aurora_snow"], location_ids=["loc-maitri"],
       related_ids=["p-geomag"], views=4310, extra={"image_count": 54, "photographer": "Wintering Team", "gallery": [IMG["aurora_snow"], IMG["milkyway_peaks"], IMG["aurora_lake"]]}, created_at="2025-06-21T09:00:00Z"),
    _c(id="m-field-team", content_type="photo", title="Field Team on the Ice Sheet",
       description="Glaciologists installing accumulation stakes on the ice sheet inland of Maitri.",
       region="Antarctica", research_area="Glaciology", author="Dr. Priya Sharma", organization="National Centre for Polar and Ocean Research", year=2026,
       tags=["Field Observation", "Glaciology", "Antarctica", "Expedition"], thumbnail=IMG["field_researcher"], location_ids=["loc-maitri"],
       related_ids=["p-snowacc"], views=1660, extra={"image_count": 22, "photographer": "Dr. Priya Sharma", "expedition_id": "exp-antarctic-2026"}, created_at="2026-02-02T09:00:00Z"),
    _c(id="m-capetown", content_type="photo", title="Expedition Port Call — Cape Town",
       description="Cargo transfer and crew change at Cape Town before the Southern Ocean crossing.",
       region="Southern Ocean", research_area="Outreach", author="Lt. Cmdr. Arun Das", organization="Expedition Logistics & Media Team", year=2025,
       tags=["Expedition", "Logistics", "Photography"], thumbnail=IMG["cape_town"], location_ids=["loc-cape-town"],
       views=860, extra={"image_count": 18, "photographer": "Lt. Cmdr. Arun Das", "expedition_id": "exp-antarctic-2026"}, created_at="2025-12-08T09:00:00Z"),
    _c(id="m-himansh-video", content_type="video", title="Life at Himansh: A High-Altitude Cryosphere Station",
       description="A short film on daily life and glacier fieldwork at Himansh in the Chandra basin.",
       region="Himalaya", research_area="Glaciology", author="Himalayan Outreach Team", organization="National Centre for Polar and Ocean Research", year=2025,
       tags=["Himalaya", "Research Station", "Documentary", "Glaciology"], thumbnail=IMG["spiti_mountain"], location_ids=["loc-himansh"],
       related_ids=["p-chandra"], views=1720, extra={"duration": "6:48"}, created_at="2025-10-20T09:00:00Z"),
    _c(id="m-svalbard-video", content_type="video", title="Summer Fieldwork at Himadri, Svalbard",
       description="Researchers at Himadri survey glaciers, sample fjord waters and service atmospheric instruments during the Arctic summer.",
       region="Arctic", research_area="Glaciology", author="Arctic Programme Office", organization="National Centre for Polar and Ocean Research", year=2025,
       tags=["Arctic", "Expedition", "Glaciology", "Documentary"], thumbnail=IMG["norway_flag"], location_ids=["loc-himadri", "loc-brogger"],
       related_ids=["exp-arctic-2025"], views=2050, extra={"duration": "9:05", "expedition_id": "exp-arctic-2025"}, created_at="2025-09-01T09:00:00Z"),
    _c(id="m-king-penguin", content_type="photo", title="Sub-Antarctic Wildlife Encounters",
       description="King penguins and seabirds photographed during the Southern Ocean crossing.",
       region="Southern Ocean", research_area="Polar Biology", author="Expedition Media Team", organization="National Centre for Polar and Ocean Research", year=2026,
       tags=["Penguins", "Wildlife", "Southern Ocean", "Photography"], thumbnail=IMG["king_penguin"], location_ids=["loc-so-transect"],
       views=2730, extra={"image_count": 31, "photographer": "Expedition Media Team", "gallery": [IMG["king_penguin"], IMG["gentoo_rock"]]}, created_at="2026-01-05T09:00:00Z"),
    _c(id="m-satellite", content_type="photo", title="Earth Observation: Polar Cloud and Ice Systems",
       description="Satellite views illustrating how Earth observation is used to monitor clouds, sea ice and ice sheets.",
       region="Antarctica", research_area="Remote Sensing", author="Remote Sensing Team", organization="National Centre for Polar and Ocean Research", year=2026,
       tags=["Remote Sensing", "Satellite", "Sea Ice"], thumbnail=IMG["earth_iss"], location_ids=["loc-seaice-zone"],
       related_ids=["d-seaice"], views=1410, extra={"image_count": 12, "photographer": "Public-domain style satellite imagery", "gallery": [IMG["earth_iss"], IMG["earth_night"], IMG["clouds_above"]]}, created_at="2026-04-11T09:00:00Z"),
    _c(id="m-press-outreach", content_type="press_release", title="Polar Science Week 2026 Comes to New Delhi",
       description="Sample announcement of a public outreach week with exhibitions, talks by expedition members and a national student polar quiz.",
       abstract="Polar Science Week brings expedition members, scientists and students together for talks, exhibitions and a national student polar quiz. Visitors can explore a virtual tour of Maitri Station and live demonstrations of polar data. (Sample event announcement for the PolarSync prototype.)",
       region="India", research_area="Outreach", author="Outreach Cell", organization="PolarSync Prototype (sample)", year=2026,
       tags=["Press Release", "Outreach", "Education"], thumbnail=IMG["aurora_lake"], location_ids=["loc-delhi"],
       views=760, created_at="2026-09-10T09:00:00Z"),
    _c(id="m-maitri-timelapse", content_type="video", title="Polar Night Time-lapse at Maitri",
       description="Time-lapse of the night sky, aurora and stars over Maitri during the winter darkness.",
       region="Antarctica", research_area="Space Weather", author="Wintering Team", organization="National Centre for Polar and Ocean Research", year=2025,
       tags=["Aurora", "Antarctica", "Time-lapse", "Maitri"], thumbnail=IMG["milkyway_peaks"], location_ids=["loc-maitri"],
       views=3320, extra={"duration": "3:20"}, created_at="2025-08-02T09:00:00Z"),
    _c(id="m-penguin-monitoring", content_type="photo", title="Penguin Colony Monitoring — Field Photographs",
       description="Photographs from nest-count surveys used in long-term colony monitoring on the Antarctic coast.",
       region="Antarctica", research_area="Polar Biology", author="Dr. Sanjay Nair", organization="National Centre for Polar and Ocean Research", year=2025,
       tags=["Penguins", "Field Observation", "Polar Biology"], thumbnail=IMG["gentoo_snow"], location_ids=["loc-prydz"],
       related_ids=["p-penguins"], views=1980, extra={"image_count": 26, "photographer": "Dr. Sanjay Nair"}, created_at="2025-02-14T09:00:00Z"),
]

EXPEDITIONS = [
    _c(id="exp-antarctic-2026", content_type="expedition", title="Indian Antarctic Expedition 2026",
       description="Follow the 2026 austral-summer expedition from its departure in Goa across the Southern Ocean to Maitri Station, through field research and data collection, and back home.",
       abstract="The annual Indian Antarctic expedition relieves the wintering teams at Maitri and Bharati, resupplies the stations and carries out summer science programmes in atmospheric science, glaciology, geology, biology and oceanography. This expedition story links each stage of the journey to the media, datasets and papers it produced. (Sample expedition narrative.)",
       region="Antarctica", research_area="Expedition", author="Expedition Media Team", organization="National Centre for Polar and Ocean Research", year=2026,
       tags=["Expedition", "Antarctica", "Research Station", "Field Observation"], thumbnail=IMG["iceberg_lagoon"],
       location_ids=["loc-ncpor-goa", "loc-cape-town", "loc-so-transect", "loc-maitri", "loc-bharati"], related_ids=["r-iae", "m-exp-video"], views=4410,
       extra={"duration_days": 120, "members": 72, "vessel": "Ice-class research vessel", "stages": [
           {"key": "departure", "title": "Departure", "location_id": "loc-ncpor-goa", "date": "2025-11-28", "image": IMG["sea_sunset"],
            "description": "Expedition members, scientific instruments and supplies leave Goa after a flag-off ceremony. Teams finalise science plans for the season.",
            "activity": "Briefings, cargo loading and instrument checks", "related_ids": ["m-press-flagoff"]},
           {"key": "ocean", "title": "Ocean Journey", "location_id": "loc-so-transect", "date": "2025-12-10", "image": IMG["ocean_waves"],
            "description": "After a port call in Cape Town the ice-class vessel crosses the Southern Ocean fronts. Scientists sample seawater and record ocean profiles along the route.",
            "activity": "CTD casts, microplastic and plankton sampling", "related_ids": ["d-ctd", "p-microplastics", "m-vessel", "m-capetown"]},
           {"key": "station", "title": "Maitri Station", "location_id": "loc-maitri", "date": "2025-12-28", "image": IMG["snow_cabin"],
            "description": "The vessel reaches the ice shelf edge and teams are flown and convoyed inland to Maitri in the Schirmacher Oasis to relieve the wintering team.",
            "activity": "Station changeover and resupply", "related_ids": ["m-maitri-winter", "m-exp-video"]},
           {"key": "field", "title": "Field Research", "location_id": "loc-maitri", "date": "2026-01-15", "image": IMG["field_researcher"],
            "description": "Glaciologists, geologists and biologists work at field camps on the ice sheet, in the oasis lakes and along the coast near Bharati.",
            "activity": "Stake surveys, firn cores, lake sampling, penguin counts", "related_ids": ["p-snowacc", "p-microbial", "m-field-team", "m-penguins"]},
           {"key": "data", "title": "Data Collection", "location_id": "loc-bharati", "date": "2026-02-10", "image": IMG["earth_iss"],
            "description": "Atmospheric, ozone and weather records are quality-checked and archived; satellite data are validated against field observations.",
            "activity": "Data QC, archiving and satellite validation", "related_ids": ["d-maitri-aws", "d-ozone-column", "d-seaice"]},
           {"key": "return", "title": "Return", "location_id": "loc-ncpor-goa", "date": "2026-03-20", "image": IMG["nunatak_clouds"],
            "description": "Summer teams return home with samples and data. Results flow into reports, papers and PolarSync's public repository.",
            "activity": "Sample shipment, reporting and publication", "related_ids": ["r-iae"]},
       ]}, created_at="2026-03-25T09:00:00Z"),
    _c(id="exp-arctic-2025", content_type="expedition", title="Arctic Summer Campaign 2025 — Himadri",
       description="A summer field campaign at India's Arctic station in Ny-Ålesund covering glaciers, fjord oceanography and atmospheric monitoring.",
       abstract="Each Arctic summer, Indian research teams rotate through Himadri station in Ny-Ålesund to carry out glaciological surveys, service the IndARC mooring and maintain atmospheric instruments. This story follows one campaign from arrival to data delivery. (Sample expedition narrative.)",
       region="Arctic", research_area="Expedition", author="Arctic Programme Office", organization="National Centre for Polar and Ocean Research", year=2025,
       tags=["Expedition", "Arctic", "Research Station", "Glaciology"], thumbnail=IMG["norway_flag"],
       location_ids=["loc-himadri", "loc-indarc", "loc-brogger"], related_ids=["r-arctic-programme", "m-svalbard-video"], views=1880,
       extra={"duration_days": 60, "members": 14, "vessel": "Small research boats", "stages": [
           {"key": "departure", "title": "Departure", "location_id": "loc-delhi", "date": "2025-06-02", "image": IMG["clouds_above"],
            "description": "Teams fly from India to Svalbard via mainland Norway with instruments for the summer season.", "activity": "Travel and permits", "related_ids": []},
           {"key": "station", "title": "Himadri Station", "location_id": "loc-himadri", "date": "2025-06-05", "image": IMG["norway_flag"],
            "description": "Arrival in Ny-Ålesund, safety training and preparation of laboratories at Himadri.", "activity": "Station set-up", "related_ids": ["m-svalbard-video"]},
           {"key": "field", "title": "Glacier Survey", "location_id": "loc-brogger", "date": "2025-06-20", "image": IMG["snow_forest"],
            "description": "Stake and GNSS surveys on Vestre Brøggerbreen record summer melt.", "activity": "Mass-balance survey", "related_ids": ["p-brogger"]},
           {"key": "ocean", "title": "Fjord Oceanography", "location_id": "loc-indarc", "date": "2025-07-08", "image": IMG["ocean_calm"],
            "description": "The IndARC mooring is recovered, serviced and redeployed in Kongsfjorden.", "activity": "Mooring turnaround", "related_ids": ["d-indarc", "p-kongsfjorden"]},
           {"key": "data", "title": "Atmospheric Sampling", "location_id": "loc-himadri", "date": "2025-07-20", "image": IMG["aurora_ice"],
            "description": "Aerosol and greenhouse gas instruments are calibrated and data downloaded.", "activity": "Instrument calibration", "related_ids": ["d-methane", "p-blackcarbon"]},
           {"key": "return", "title": "Return", "location_id": "loc-delhi", "date": "2025-08-01", "image": IMG["aurora_lake"],
            "description": "Teams return and data are processed for the annual Arctic programme summary.", "activity": "Reporting", "related_ids": ["r-arctic-programme"]},
       ]}, created_at="2025-08-10T09:00:00Z"),
]

EDUCATION = [
    _c(id="story-antarctica", content_type="story", title="How India Studies Antarctica",
       description="From the first expedition in 1981 to year-round science at Maitri and Bharati — a scroll-through story of India's Antarctic programme.",
       region="Antarctica", research_area="Outreach", author="PolarSync Outreach", organization="PolarSync", year=2026,
       tags=["Outreach", "Antarctica", "Expedition", "Research Station"], thumbnail=IMG["iceberg_lagoon"], location_ids=["loc-maitri", "loc-bharati", "loc-dakshin"],
       views=5210, extra={"href": "/education/stories/story-antarctica", "duration": "8 min read", "level": "General"}, created_at="2026-02-01T09:00:00Z"),
    _c(id="story-arctic", content_type="story", title="The Arctic Is Changing — Why It Matters to India",
       description="A data-driven story on Arctic sea-ice decline, warming fjords and the questions Indian scientists study at Himadri.",
       region="Arctic", research_area="Outreach", author="PolarSync Outreach", organization="PolarSync", year=2026,
       tags=["Outreach", "Arctic", "Sea Ice", "Climate Change"], thumbnail=IMG["aurora_trees"], location_ids=["loc-himadri"],
       views=3120, extra={"href": "/education/stories/story-arctic", "duration": "6 min read", "level": "General"}, created_at="2026-03-01T09:00:00Z"),
    _c(id="story-third-pole", content_type="story", title="The Third Pole: Himalayan Glaciers",
       description="Why the Himalaya is called the Third Pole, how its glaciers feed rivers and how scientists at Himansh monitor them.",
       region="Himalaya", research_area="Outreach", author="PolarSync Outreach", organization="PolarSync", year=2026,
       tags=["Outreach", "Himalaya", "Glaciology", "Hydrology"], thumbnail=IMG["himalaya_ama"], location_ids=["loc-himansh", "loc-gangotri"],
       views=2870, extra={"href": "/education/stories/story-third-pole", "duration": "7 min read", "level": "General"}, created_at="2026-04-01T09:00:00Z"),
    _c(id="story-penguins", content_type="story", title="Penguins: Sentinels of the Southern Ocean",
       description="Meet the penguins of Prydz Bay and learn how counting nests helps scientists read the health of the ocean.",
       region="Antarctica", research_area="Outreach", author="PolarSync Outreach", organization="PolarSync", year=2026,
       tags=["Outreach", "Penguins", "Polar Biology"], thumbnail=IMG["gentoo_snow"], location_ids=["loc-prydz"],
       views=4020, extra={"href": "/education/stories/story-penguins", "duration": "5 min read", "level": "Young learners"}, created_at="2026-05-01T09:00:00Z"),
    _c(id="tour-maitri", content_type="tour", title="Explore Maitri Research Station",
       description="An interactive tour of Maitri: click hotspots to visit the laboratory, living quarters, observatory and weather station.",
       region="Antarctica", research_area="Outreach", author="PolarSync Outreach", organization="PolarSync", year=2026,
       tags=["Virtual Tour", "Maitri", "Research Station", "Antarctica"], thumbnail=IMG["snow_cabin"], location_ids=["loc-maitri"],
       views=3640, extra={"href": "/education/tour/tour-maitri", "duration": "10 min", "level": "All ages"}, created_at="2026-02-15T09:00:00Z"),
    _c(id="tour-himadri", content_type="tour", title="Himadri Arctic Station Walkthrough",
       description="Visit India's Arctic station in Ny-Ålesund and discover its glacier, fjord and atmosphere research.",
       region="Arctic", research_area="Outreach", author="PolarSync Outreach", organization="PolarSync", year=2026,
       tags=["Virtual Tour", "Himadri", "Arctic", "Research Station"], thumbnail=IMG["norway_flag"], location_ids=["loc-himadri"],
       views=1750, extra={"href": "/education/tour/tour-himadri", "duration": "8 min", "level": "All ages"}, created_at="2026-03-15T09:00:00Z"),
    _c(id="quiz-polar", content_type="quiz", title="How Much Do You Know About the Polar Regions?",
       description="Ten questions on Antarctica, the Arctic and India's polar stations. Earn your Polar Explorer level.",
       region="Antarctica", research_area="Outreach", author="PolarSync Outreach", organization="PolarSync", year=2026,
       tags=["Quiz", "Outreach", "Antarctica", "Arctic"], thumbnail=IMG["chinstrap_snow"], location_ids=[],
       views=6890, extra={"href": "/education/quiz/quiz-polar", "duration": "5 min", "level": "Intermediate", "questions": 10}, created_at="2026-01-10T09:00:00Z"),
    _c(id="quiz-cryo", content_type="quiz", title="Glaciers and the Third Pole Quiz",
       description="Eight questions about glaciers, snow and the Himalayan cryosphere.",
       region="Himalaya", research_area="Outreach", author="PolarSync Outreach", organization="PolarSync", year=2026,
       tags=["Quiz", "Outreach", "Himalaya", "Glaciology"], thumbnail=IMG["peaks_clouds"], location_ids=[],
       views=2210, extra={"href": "/education/quiz/quiz-cryo", "duration": "4 min", "level": "Beginner", "questions": 8}, created_at="2026-04-10T09:00:00Z"),
    _c(id="kit-classroom", content_type="kit", title="Polar Science Classroom Pack",
       description="Lesson plans, worksheets and discussion prompts for teaching polar science to students aged 12–18.",
       region="Antarctica", research_area="Outreach", author="PolarSync Outreach", organization="PolarSync", year=2026,
       tags=["Educator Kit", "Outreach", "Classroom"], thumbnail=IMG["field_researcher"], location_ids=[],
       views=1980, extra={"href": "/education/kits#kit-classroom", "duration": "4 lessons", "level": "Secondary"}, created_at="2026-02-20T09:00:00Z"),
    _c(id="kit-seaice", content_type="kit", title="Sea Ice Data Activity",
       description="Students plot real-style sea-ice extent values, spot seasonal cycles and discuss long-term change.",
       region="Antarctica", research_area="Outreach", author="PolarSync Outreach", organization="PolarSync", year=2026,
       tags=["Educator Kit", "Sea Ice", "Data Literacy"], thumbnail=IMG["earth_iss"], location_ids=[], related_ids=["d-seaice"],
       views=1240, extra={"href": "/education/kits#kit-seaice", "duration": "1 lesson", "level": "Secondary"}, created_at="2026-03-20T09:00:00Z"),
    _c(id="kit-glacier", content_type="kit", title="Teacher's Guide: Glaciers and Climate",
       description="Hands-on experiments and background notes explaining how glaciers form, move and respond to climate.",
       region="Himalaya", research_area="Outreach", author="PolarSync Outreach", organization="PolarSync", year=2026,
       tags=["Educator Kit", "Glaciology", "Himalaya"], thumbnail=IMG["himalaya_peak"], location_ids=[],
       views=1105, extra={"href": "/education/kits#kit-glacier", "duration": "2 lessons", "level": "Middle school"}, created_at="2026-04-20T09:00:00Z"),
]

# Submissions awaiting review. Content rows are created with status
# 'under_review'; AI analysis is computed at seed time by AIService.
PENDING_SUBMISSIONS = [
    {"submitted_by": "u-priya", "submitted_at": "2026-10-01T08:30:00Z", "notes": "Requesting review before the SCAR open science conference.",
     "content": _c(id="c-icecore", content_type="paper", status="under_review", title="Antarctic Ice Core Analysis — Stable Isotope Records 2015–2024",
        description="Stable water isotope measurements from a shallow ice core drilled inland of Maitri, used to reconstruct recent temperature and accumulation variability.",
        abstract="A shallow ice core was drilled on the ice sheet inland of Maitri Station during the austral summer field season. Stable oxygen and hydrogen isotope ratios were measured at high resolution and dated using annual layer counting and volcanic reference horizons. The isotope record is compared with Maitri weather station temperatures and reanalysis data to evaluate its value as a climate proxy. Accumulation rates derived from the core are discussed alongside stake-network measurements. The record extends local palaeoclimate information for coastal Dronning Maud Land.",
        region="Antarctica", research_area="Glaciology", author="Dr. Priya Sharma", organization="National Centre for Polar and Ocean Research", year=2026,
        tags=[], thumbnail=IMG["snow_slope"], file_format="PDF", file_size="3.4 MB", file_name="icecore_isotopes_2026.pdf", location_ids=["loc-maitri"], created_at="2026-10-01T08:30:00Z")},
    {"submitted_by": "u-meera", "submitted_at": "2026-09-28T11:15:00Z", "notes": "HPLC pigment data from two expedition transects.",
     "content": _c(id="c-phyto-pigments", content_type="dataset", status="under_review", title="Southern Ocean Phytoplankton Pigment Dataset (HPLC)",
        description="High-performance liquid chromatography (HPLC) phytoplankton pigment concentrations from surface water samples collected along the Southern Ocean expedition transect.",
        abstract="This dataset contains phytoplankton pigment concentrations measured by HPLC from surface seawater samples collected at stations between Cape Town and the Antarctic coast. Chlorophyll a and accessory pigments are reported with sample position, date and frontal zone. Derived phytoplankton group composition is provided. The data support studies of bloom dynamics and the Southern Ocean food web. Files are provided as CSV with a data dictionary.",
        region="Southern Ocean", research_area="Oceanography", author="Dr. Meera Pillai", organization="CSIR – National Institute of Oceanography", year=2026,
        tags=[], thumbnail=IMG["ocean_waves"], file_format="CSV", file_size="18 MB", file_name="so_hplc_pigments.csv", location_ids=["loc-so-transect"], created_at="2026-09-28T11:15:00Z")},
    {"submitted_by": "u-rajesh", "submitted_at": "2026-09-25T09:00:00Z", "notes": "Annual snow cover trend report derived from MODIS.",
     "content": _c(id="c-snowcover", content_type="report", status="under_review", title="Himalayan Snow Cover Trend Report 2020–2025",
        description="Assessment of seasonal snow cover in the Indian Himalaya from daily MODIS snow products, with basin-wise trends and implications for water resources.",
        abstract="This report assesses seasonal snow cover across Himalayan river basins using daily MODIS satellite snow products for 2020 to 2025. Cloud gaps are filled using temporal interpolation. Basin-wise snow-covered area, snow onset and melt timing are summarised. The report discusses implications of snow cover variability for spring runoff and water resources and recommends improved ground validation at high-altitude stations such as Himansh.",
        region="Himalaya", research_area="Remote Sensing", author="Dr. Rajesh Kumar", organization="Wadia Institute of Himalayan Geology", year=2026,
        tags=[], thumbnail=IMG["peaks_clouds"], file_format="PDF", file_size="7.9 MB", file_name="himalayan_snow_cover_2025.pdf", location_ids=["loc-himansh"], created_at="2026-09-25T09:00:00Z")},
    {"submitted_by": "u-arun", "submitted_at": "2026-10-02T14:00:00Z", "notes": "High-resolution wildlife and landscape photography.",
     "content": _c(id="c-bharati-photos", content_type="photo", status="under_review", title="Bharati Station Wildlife Photography 2026",
        description="A photograph collection of penguins, seals and seabirds around the Larsemann Hills and Bharati Station during the 2026 summer season.",
        abstract="Image collection documenting wildlife near Bharati Station in the Larsemann Hills, including Adélie penguins, Weddell seals and snow petrels, as well as coastal landscapes and sea ice. Images were taken from permitted distances following wildlife-disturbance guidelines. Each photograph includes date, location and species information.",
        region="Antarctica", research_area="Polar Biology", author="Lt. Cmdr. Arun Das", organization="Expedition Logistics & Media Team", year=2026,
        tags=[], thumbnail=IMG["gentoo_rock"], file_format="JPEG (ZIP)", file_size="1.6 GB", file_name="bharati_wildlife_2026.zip", location_ids=["loc-bharati", "loc-prydz"],
        extra={"image_count": 64, "photographer": "Lt. Cmdr. Arun Das", "gallery": [IMG["gentoo_rock"], IMG["chinstrap_snow"], IMG["king_penguin"]]}, created_at="2026-10-02T14:00:00Z")},
    {"submitted_by": "u-ananya", "submitted_at": "2026-09-30T10:20:00Z", "notes": "Winter radiosonde campaign profiles.",
     "content": _c(id="c-radiosonde", content_type="dataset", status="under_review", title="Radiosonde Profiles from Maitri — Winter 2025",
        description="Vertical profiles of temperature, humidity and wind from balloon-borne radiosondes launched at Maitri during the 2025 winter.",
        abstract="Daily radiosonde launches at Maitri Station during the 2025 polar winter recorded vertical profiles of air temperature, relative humidity, pressure and wind up to the lower stratosphere. Profiles are quality controlled and provided at standard pressure levels and full resolution. The dataset supports studies of the Antarctic boundary layer, polar vortex and weather forecasting.",
        region="Antarctica", research_area="Atmospheric Science", author="Dr. Ananya Krishnan", organization="National Centre for Polar and Ocean Research", year=2026,
        tags=[], thumbnail=IMG["clouds_above"], file_format="NetCDF", file_size="64 MB", file_name="maitri_radiosonde_2025.nc", location_ids=["loc-maitri"], created_at="2026-09-30T10:20:00Z")},
    {"submitted_by": "u-alex", "submitted_at": "2026-09-22T16:45:00Z", "notes": "Manuscript version 2.",
     "content": _c(id="c-sentinel-velocity", content_type="paper", status="under_review", title="Glacier Surface Velocity Mapping in Svalbard Using Sentinel-1",
        description="Applies radar offset tracking to Sentinel-1 imagery to map seasonal glacier surface velocity around Kongsfjorden, Svalbard.",
        abstract="Glacier flow speed responds to meltwater reaching the glacier bed. This study applies synthetic aperture radar offset tracking to Sentinel-1 satellite imagery to map glacier surface velocity around Kongsfjorden in Svalbard. Seasonal speed-up during the melt season is examined for tidewater and land-terminating glaciers. Velocity maps are validated with GNSS measurements on Vestre Brøggerbreen collected by teams from Himadri.",
        region="Arctic", research_area="Remote Sensing", author="Alex Johnson", organization="National Centre for Polar and Ocean Research", year=2026,
        tags=[], thumbnail=IMG["snow_forest"], file_format="PDF", file_size="5.6 MB", file_name="sentinel1_velocity_svalbard.pdf", location_ids=["loc-himadri", "loc-brogger"], created_at="2026-09-22T16:45:00Z")},
]

# Alex's other non-published items (draft and changes requested)
CONTRIBUTOR_EXTRA = [
    {"submitted_by": "u-alex", "submission_status": None, "notes": None,
     "content": _c(id="c-draft-rivers", content_type="paper", status="draft", title="Microplastics in Himalayan Glacier-fed Rivers (draft)",
        description="Early-stage draft on sampling microplastics in rivers fed by Himalayan glaciers.",
        region="Himalaya", research_area="Hydrology", author="Alex Johnson", organization="National Centre for Polar and Ocean Research", year=2026,
        tags=["Marine Pollution", "Himalaya", "Hydrology"], thumbnail=IMG["himalaya_peak"], location_ids=["loc-gangotri"], created_at="2026-09-20T08:30:00Z")},
    {"submitted_by": "u-alex", "submission_status": "changes_requested", "submitted_at": "2026-08-30T10:00:00Z", "notes": "First submission.",
     "review_comment": "Please add sampling dates and instrument details to the metadata, and clarify the licence for the raw spectra.",
     "content": _c(id="c-snowchem", content_type="dataset", status="changes_requested", title="Snow Chemistry Samples — Ny-Ålesund 2025",
        description="Major-ion and black-carbon concentrations in surface snow samples collected around Ny-Ålesund.",
        abstract="Surface snow samples collected around Ny-Ålesund were analysed for major ions and black carbon to examine deposition of pollutants transported to the Arctic.",
        region="Arctic", research_area="Atmospheric Science", author="Alex Johnson", organization="National Centre for Polar and Ocean Research", year=2026,
        tags=["Aerosols", "Snow", "Arctic"], thumbnail=IMG["aurora_trees"], location_ids=["loc-himadri"], created_at="2026-08-30T10:00:00Z")},
]

# Published items that went through the review workflow (history for admin tabs)
APPROVED_HISTORY = [
    ("p-brogger", "u-alex", "2026-05-12T10:00:00Z", "2026-05-19T09:00:00Z", "Metadata complete. Approved for publication."),
    ("d-ctd", "u-meera", "2026-03-28T10:00:00Z", "2026-04-04T09:00:00Z", "Well-documented dataset; approved."),
    ("p-phyto", "u-meera", "2026-02-01T10:00:00Z", "2026-02-09T09:00:00Z", "Approved after minor keyword edits."),
    ("m-press-outreach", "u-arun", "2026-09-05T10:00:00Z", "2026-09-10T09:00:00Z", "Approved."),
]

REJECTED_HISTORY = [
    {"submitted_by": "u-farhan", "submitted_at": "2026-07-14T09:00:00Z", "decided_at": "2026-07-18T09:00:00Z",
     "comment": "Duplicate of an existing record (Rock Glaciers and Mountain Permafrost in the Western Himalaya).",
     "content": _c(id="c-dup-permafrost", content_type="paper", status="rejected", title="Rock Glacier Inventory of Spiti Valley (duplicate upload)",
        description="Duplicate upload of the rock-glacier inventory study.", region="Himalaya", research_area="Geology", author="Dr. Farhan Ali",
        organization="Geological Survey (collaborating institute)", year=2026, tags=["Permafrost", "Himalaya"], thumbnail=IMG["spiti_mountain"], location_ids=["loc-himansh"],
        created_at="2026-07-14T09:00:00Z")},
]

POPULAR_QUERIES = [
    ("climate change", 18), ("antarctic ice", 15), ("sea ice dataset", 12), ("maitri station", 11), ("glacier retreat himalaya", 10),
    ("penguins", 9), ("ozone hole", 7), ("arctic methane", 6), ("ice shelf", 8), ("aurora", 6), ("ocean microplastics", 5),
    ("himadri svalbard", 5), ("expedition 2026", 7), ("snow cover", 4), ("permafrost", 3),
]
